Repository Clariteia/api_gateway_common, pull requests merged in 2021-05, with the labels that each got.

#7 MinosConfig
  .github/workflows/python-tests.yml
  .gitignore
  .idea/api_gateway_common.iml
  minos/api_gateway/__init__.py
  minos/api_gateway/common/__init__.py
  minos/api_gateway/common/configuration/__init__.py
  minos/api_gateway/common/configuration/config.py
  minos/api_gateway/common/exceptions.py
  requirements_dev.txt
  tests/test_api_gateway/__init__.py
  tests/test_api_gateway/test_common/__init__.py
  tests/test_api_gateway/test_common/test_configuration/__init__.py
  tests/test_api_gateway/test_common/test_configuration/test_config.py
  tests/test_api_gateway/test_common/test_exceptions.py
  tests/test_api_gateway_common.py
  tests/test_config.yml
  tests/utils.py
Labels: enhancement

#12 Add importlib
  minos/api_gateway/__init__.py
  minos/api_gateway/common/__init__.py
  minos/api_gateway/common/client/__init__.py
  minos/api_gateway/common/client/abc.py
  minos/api_gateway/common/client/client.py
  minos/api_gateway/common/importlib.py
  requirements_dev.txt
  setup.py
  tests/ImportedModule.py
  tests/test_api_gateway/test_common/test_client/__init__.py
  tests/test_api_gateway/test_common/test_client/test_abc.py
  tests/test_api_gateway/test_common/test_importlib.py
Labels: enhancement

#17 REST aiohttp handler and extensible service
  minos/api_gateway/__init__.py
  minos/api_gateway/common/__init__.py
  minos/api_gateway/common/rest/__init__.py
  minos/api_gateway/common/rest/loader.py
  minos/api_gateway/common/rest/service.py
  requirements_dev.txt
  tests/services/TestRestService.py
  tests/test_api_gateway/test_common/test_client/test_abc.py
  tests/test_api_gateway/test_common/test_exceptions.py
  tests/test_api_gateway/test_common/test_importlib.py
  tests/test_api_gateway/test_common/test_rest_interface/__init__.py
  tests/test_api_gateway/test_common/test_rest_interface/test_loader.py
  tests/test_api_gateway/test_common/test_rest_interface/test_service.py
  tests/test_config.yml
Labels: enhancement

#28 #5 (remove `.idea` files)
  .gitignore
  .idea/.gitignore
  .idea/api_gateway_common.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: meta

#30 Default MinosConfig RestRoutesLoader
  minos/api_gateway/common/rest/loader.py
  minos/api_gateway/common/rest/service.py
  tests/services/TestRestService.py
  tests/test_api_gateway/test_common/test_rest_interface/test_loader.py
  tests/test_api_gateway/test_common/test_rest_interface/test_service.py
Labels: enhancement

#33 #26 (update `.gitignore`)
  .gitignore
Labels: meta

#36 HttpClient close connection
  minos/api_gateway/common/client/client.py
  tests/test_api_gateway/test_common/test_client/test_abc.py
Labels: bug

#40 BUG: AttributeError: 'Discovery' object has no attribute 'path'
  minos/api_gateway/common/configuration/config.py
  tests/test_api_gateway/test_common/test_configuration/test_config.py
Labels: bug
